### ISSUE TITLE
filepath-bytestring does not follow an open-development model? hpath-filepath/README.md

### ISSUE THREAD

**Issue by legrostdg** [hasufell/hpath#30]
In `hpath-filepath/README.md` we can read `There is also a similar library filepath-bytestring, but it doesn't follow an open development model and is cross-platform, which this library is not interested in.`

What do you mean by "doesn't follow an open development model"? It seems to be open-source.

**Comment by hasufell** [comment]
> What do you mean by "doesn't follow an open development model"? It seems to be open-source.

Open source does not mean "open development model". Open source is about the LICENSE, not the workflow. In order to qualify for "open development model", a project has to:

* have a place for open discussions (issue tracker, ML, IRC or similar), for PRs, ideas, decisions
* have a way for users to observe the development process (open git repository)
* have an *easy* way to contribute and that contribution process should be publicly visible (e.g. patches can be commented on by other people during the contribution process)
